server:
  port: 8089
  http2:
    enabled: true
  undertow:
    buffer-size: 1024
    direct-buffers: true
    max-http-post-size: 1000
    threads:
      io: 4
      worker: 8

app:
  env: LOCAL

spring:
  application:
    name: Ketchup

  servlet:
    multipart:
      file-size-threshold: 10485760
      max-file-size: 1MB

  mvc:
    throw-exception-if-no-handler-found: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ketchup?useUnicode=true&characterEncoding=utf8&&autoReconnect=true&useSSL=false&&serverTimezone=CTT
    username: root
    password: lomofu
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-test-query: SELECT 1


