spring:
  profiles:
    active: @profileActive@
  application:
    name: Ketchup

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.fwll.*.domain
